export const blogPosts = [
  // ─── ORIGINAL 3 ───────────────────────────────────────────────────────────
  {
    slug: "write-ats-friendly-resume",
    title: "How to Write an ATS-Friendly Resume in 2026",
    excerpt:
      "Learn how to structure your CV so applicant tracking systems and recruiters can read it clearly — and actually call you back.",
    category: "Resume Tips",
    date: "Jan 12, 2026",
    readTime: "6 min read",
    author: "CVPair Team",
    image: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=1200&q=80",
    content_blocks: [
      { type: "paragraph", text: "Most companies today use applicant tracking systems (ATS) to filter CVs before a human ever reads them. If your CV is not formatted correctly, it may be rejected automatically — even if you are the right candidate for the job." },
      { type: "heading", text: "What Is an ATS and Why Does It Matter?", level: 2 },
      { type: "paragraph", text: "An ATS is software that scans, parses, and ranks CVs based on keywords, formatting, and relevance to the job description. Companies like Workday, Greenhouse, and Lever are used by the majority of mid-to-large employers. Your CV must be readable by both the machine and the hiring manager." },
      { type: "heading", text: "Use a Clean, Single-Column Layout", level: 2 },
      { type: "paragraph", text: "ATS software struggles with tables, text boxes, headers and footers, and multi-column layouts. Use a single-column format with clear section headings. Avoid placing your contact information in a header — some systems cannot read it." },
      { type: "heading", text: "Match Keywords From the Job Description", level: 2 },
      { type: "paragraph", text: "Read the job posting carefully and identify the key skills, tools, and phrases the employer uses. Mirror those words in your CV — particularly in your summary, skills section, and experience bullets. Do not keyword-stuff; use them where they make sense." },
      { type: "heading", text: "Use Standard Section Headings", level: 2 },
      { type: "list", items: ["Work Experience (not Career History or Professional Journey)", "Education (not Academic Background)", "Skills (not Core Competencies or Toolbox)", "Certifications (not Credentials)"] },
      { type: "paragraph", text: "ATS systems are trained to look for standard labels. Clever or creative section names are often missed entirely." },
      { type: "heading", text: "Format Your Dates Consistently", level: 2 },
      { type: "paragraph", text: "Use a consistent date format throughout: Month Year or MM/YYYY. For example: January 2023 – March 2025. Inconsistent formatting can cause ATS to misread your timeline." },
      { type: "heading", text: "Save in the Right File Format", level: 2 },
      { type: "paragraph", text: "Unless the job posting specifies otherwise, submit your CV as a .docx or .pdf. Most modern ATS can read both, but check the application instructions first. CVPair lets you export a clean PDF with one click." },
      { type: "callout", text: "Tip: After writing your CV, use CVPair's built-in ATS checklist to score your document against 7 recruiter criteria before you apply." },
      { type: "cta", text: "Build an ATS-Ready CV Now", href: "/resume", buttonText: "Open CV Builder" },
    ],
  },
  {
    slug: "resume-template-for-product-managers",
    title: "Best Resume Template for Product Managers",
    excerpt:
      "A product manager resume should show strategy, execution, metrics, and cross-functional leadership. Here is how to structure yours.",
    category: "Templates",
    date: "Jan 20, 2026",
    readTime: "5 min read",
    author: "CVPair Team",
    image: "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1200&q=80",
    content_blocks: [
      { type: "paragraph", text: "Product managers sit at the intersection of business, technology, and user experience. Your CV needs to reflect that breadth — while staying focused on the outcomes you drove." },
      { type: "heading", text: "Lead With Impact, Not Tasks", level: 2 },
      { type: "paragraph", text: "The most common PM resume mistake is listing responsibilities instead of results. Recruiters already know what a PM does. They want to know what you specifically achieved. Every bullet should answer: what changed because of you?" },
      { type: "heading", text: "Key Sections for a PM Resume", level: 2 },
      { type: "list", items: ["Professional Summary — 2–3 lines on your PM focus, industry, and scale", "Core Competencies — roadmapping, A/B testing, stakeholder management, OKRs", "Experience — company, role, dates, 4–6 impact bullets per role", "Selected Projects or Products — with metrics (MAU, revenue, retention)", "Education — degree and institution", "Certifications — CSPO, PMP, Google PM Certificate (if relevant)"] },
      { type: "heading", text: "Metrics That Matter for PMs", level: 2 },
      { type: "paragraph", text: "Quantify wherever possible. The numbers that resonate in PM resumes include: monthly active users, revenue growth, conversion rate improvements, NPS score changes, time-to-market reduction, and cost savings." },
      { type: "heading", text: "Which Template to Use", level: 2 },
      { type: "paragraph", text: "Use the MBA or Product Manager template on CVPair. Both prioritise the experience section while giving room for metrics and product context. Avoid overly creative layouts — most PM roles go through ATS first." },
      { type: "callout", text: "Example bullet: Launched onboarding redesign that improved 30-day retention by 22% and reduced support tickets by 35% across 120,000 monthly active users." },
      { type: "cta", text: "Try the Product Manager Template", href: "/resume?productManager", buttonText: "Open Template" },
    ],
  },
  {
    slug: "common-resume-mistakes",
    title: "10 CV Mistakes That Cost You Interviews",
    excerpt:
      "Small mistakes on your CV can quietly kill your chances. Here are the ten most common problems and exactly how to fix them.",
    category: "Career Advice",
    date: "Feb 2, 2026",
    readTime: "7 min read",
    author: "CVPair Team",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80",
    content_blocks: [
      { type: "paragraph", text: "Most CVs are rejected not because of a bad career — but because of avoidable formatting, content, or strategy mistakes. Here are ten patterns that consistently hurt candidates, and how to fix each one." },
      { type: "heading", text: "1. Writing Responsibilities Instead of Achievements", level: 2 },
      { type: "paragraph", text: "Listing what your job was is not the same as showing what you did. Replace 'Responsible for managing social media accounts' with 'Grew Instagram following from 4,000 to 28,000 in 8 months through targeted content strategy.'" },
      { type: "heading", text: "2. Sending the Same CV to Every Job", level: 2 },
      { type: "paragraph", text: "A generic CV rarely wins. Tailor your summary, skills, and top bullets to match the language and priorities in each job description." },
      { type: "heading", text: "3. Including Irrelevant Personal Information", level: 2 },
      { type: "paragraph", text: "Marital status, date of birth, nationality, and a photo are not required on CVs in most countries and can introduce unconscious bias. Remove them unless the employer specifically asks." },
      { type: "heading", text: "4. Weak or Missing Professional Summary", level: 2 },
      { type: "paragraph", text: "Your summary is the first thing a hiring manager reads. If it is vague ('Motivated professional seeking a challenging role'), you lose them immediately. Be specific about your field, years of experience, and top strength." },
      { type: "heading", text: "5. Poor Formatting and Visual Clutter", level: 2 },
      { type: "paragraph", text: "Multiple fonts, dense paragraphs, bright colours, and unusual layouts make your CV harder to read — and harder for ATS to parse. Keep it clean, consistent, and scannable." },
      { type: "heading", text: "6. Leaving Dates Vague or Inconsistent", level: 2 },
      { type: "paragraph", text: "Use the same date format throughout (Month Year or MM/YYYY). Vague entries like '2021–2023' without months can raise questions about gaps you are not hiding." },
      { type: "heading", text: "7. A CV That Is Too Long or Too Short", level: 2 },
      { type: "paragraph", text: "One page is ideal for 0–3 years of experience. Two pages for 3–10 years. Beyond 10 years, two pages is still the maximum in most industries. Never pad to fill space — cut ruthlessly." },
      { type: "heading", text: "8. Broken Links or Wrong Contact Details", level: 2 },
      { type: "paragraph", text: "A wrong email address or a dead portfolio link can cost you the interview. Test every link before you submit. Make sure your email is professional — firstname.lastname@gmail.com, not partyguy99@hotmail.com." },
      { type: "heading", text: "9. Skills Section With No Context", level: 2 },
      { type: "paragraph", text: "Listing 'Microsoft Office' or 'good communicator' without any evidence is meaningless. Either back up soft skills with examples in your experience, or remove them from the skills list." },
      { type: "heading", text: "10. No Proofreading", level: 2 },
      { type: "paragraph", text: "Spelling and grammar errors signal carelessness. Read your CV aloud, use a spell checker, and ask a trusted friend to review it before you apply anywhere." },
      { type: "cta", text: "Fix These Issues in CVPair", href: "/resume", buttonText: "Build Your CV" },
    ],
  },

  // ─── 20 NEW ARTICLES ──────────────────────────────────────────────────────
  {
    slug: "how-to-write-a-professional-cv-2026",
    title: "How to Write a Professional CV in 2026",
    excerpt:
      "A step-by-step guide to writing a CV that gets noticed in 2026 — covering structure, formatting, content, and common mistakes to avoid.",
    category: "CV Writing",
    date: "Feb 10, 2026",
    readTime: "8 min read",
    author: "CVPair Team",
    image: "https://images.unsplash.com/photo-1586281380349-632531db7ed4?auto=format&fit=crop&w=1200&q=80",
    content_blocks: [
      { type: "paragraph", text: "A professional CV is your personal marketing document. It needs to convince a hiring manager — in under 10 seconds — that you are worth interviewing. In 2026, that means balancing clean design, clear writing, and ATS compatibility." },
      { type: "heading", text: "Start With the Right Structure", level: 2 },
      { type: "paragraph", text: "A professional CV follows a logical order that makes it easy for recruiters to find what they need quickly. Hiring managers scan in an F-pattern — the top of your CV gets the most attention." },
      { type: "list", items: [
        "Contact information (name, email, phone, LinkedIn, location)",
        "Professional summary (2–4 lines)",
        "Work experience (most recent first)",
        "Education",
        "Skills",
        "Certifications or additional sections (optional)",
      ]},
      { type: "heading", text: "Write a Focused Professional Summary", level: 2 },
      { type: "paragraph", text: "Your summary sits at the top and sets the tone. It should answer three questions: Who are you? What do you specialise in? What value do you bring? Example: 'Marketing manager with 6 years of experience in B2B SaaS. Specialises in demand generation and pipeline growth. Led campaigns that generated £2.4M in qualified pipeline across EMEA.'" },
      { type: "heading", text: "Make Your Experience Section Count", level: 2 },
      { type: "paragraph", text: "List your last three to four roles. For each, include: the company name, your job title, the dates (month and year), and three to five bullet points. Each bullet should start with a strong action verb and ideally include a measurable result." },
      { type: "callout", text: "Weak: 'Helped with sales team activities.' Strong: 'Supported outbound sales team by building a prospecting workflow that reduced average deal cycle by 18 days.'" },
      { type: "heading", text: "Keep Education Concise", level: 2 },
      { type: "paragraph", text: "Unless you are a recent graduate, your education section should be brief — degree title, institution name, and graduation year. Do not list every module you studied. GPA is only worth including if it was exceptional and you graduated within the last three years." },
      { type: "heading", text: "Choose the Right Format for Your Industry", level: 2 },
      { type: "paragraph", text: "Most professionals should use a chronological or hybrid format. A chronological CV lists experience in reverse date order — most recent first. A hybrid adds a skills summary at the top before experience. Functional CVs (skills-only, no dates) are generally not recommended as they raise red flags with recruiters." },
      { type: "heading", text: "Formatting Rules That Still Matter", level: 2 },
      { type: "list", items: [
        "Font: Use a professional font — Calibri, Georgia, or Helvetica at 10–12pt",
        "Margins: 1 to 1.5cm all around",
        "Length: One page for under 5 years experience, two pages for more",
        "File: Submit as PDF unless told otherwise",
        "Colour: Use sparingly — a single accent colour is fine, rainbow headings are not",
      ]},
      { type: "cta", text: "Build Your Professional CV Today", href: "/resume", buttonText: "Start for Free" },
    ],
  },

  {
    slug: "best-cv-format-fresh-graduates",
    title: "Best CV Format for Fresh Graduates",
    excerpt:
      "No experience? No problem. This guide shows fresh graduates exactly how to structure a CV that stands out — even with a limited work history.",
    category: "CV Writing",
    date: "Feb 14, 2026",
    readTime: "6 min read",
    author: "CVPair Team",
    image: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=1200&q=80",
    content_blocks: [
      { type: "paragraph", text: "As a fresh graduate, you are competing with hundreds of other candidates who also have limited work experience. The good news: your CV is not about experience alone — it is about potential, relevance, and how well you present what you do have." },
      { type: "heading", text: "Put Education First", level: 2 },
      { type: "paragraph", text: "Unlike experienced candidates who lead with work history, fresh graduates should place education near the top. Include your degree title, university name, graduation year, and your grade or classification if it is strong. You can also add a line on relevant modules, thesis topic, or academic awards." },
      { type: "heading", text: "Use a Skills-Forward Summary", level: 2 },
      { type: "paragraph", text: "Your summary should position you for the role — not apologise for lack of experience. Focus on what you studied, what you are good at, and what you are looking to do. Example: 'Recent BSc Computer Science graduate from the University of Manchester. Strong foundation in Python, data structures, and software development. Looking to apply problem-solving skills in a junior developer role.'" },
      { type: "heading", text: "Make the Most of Non-Traditional Experience", level: 2 },
      { type: "paragraph", text: "Work experience does not only mean full-time jobs. The following all count and should be included:" },
      { type: "list", items: [
        "Internships and placements (even short ones)",
        "Part-time or casual work (retail, hospitality — shows reliability)",
        "Freelance or self-started projects",
        "University society roles (president, treasurer, events lead)",
        "Volunteering",
        "Hackathons, competitions, or research projects",
      ]},
      { type: "heading", text: "Build a Strong Skills Section", level: 2 },
      { type: "paragraph", text: "List both technical and transferable skills relevant to the role. For technical roles: programming languages, tools, or platforms. For business roles: Excel, Canva, Google Analytics, project management tools. For all roles: communication, teamwork, and problem-solving are worth including — but only if backed up by an example elsewhere on your CV." },
      { type: "heading", text: "Keep It to One Page", level: 2 },
      { type: "paragraph", text: "A fresh graduate CV should almost always be one page. Remove secondary school results unless they are exceptional. Cut the objective statement if it is generic. Do not pad with filler. Whitespace is not wasted space — it makes your CV easier to read." },
      { type: "callout", text: "Use CVPair's Compact or Modern template — both are designed to present a clean, professional one-page CV even when your experience is limited." },
      { type: "cta", text: "Build Your Graduate CV", href: "/resume?compact", buttonText: "Open CV Builder" },
    ],
  },

  {
    slug: "cv-vs-resume-difference",
    title: "CV vs Resume: What Is the Difference?",
    excerpt:
      "CV and resume are often used interchangeably — but they are not the same document. Here is when to use each and what goes in them.",
    category: "CV Writing",
    date: "Feb 18, 2026",
    readTime: "5 min read",
    author: "CVPair Team",
    image: "https://images.unsplash.com/photo-1568992687947-868a62a9f521?auto=format&fit=crop&w=1200&q=80",
    content_blocks: [
      { type: "paragraph", text: "The terms CV and resume are used interchangeably in many countries — but in the UK, Europe, and academic or research contexts, they mean different things. Understanding which one to send can affect whether your application is taken seriously." },
      { type: "heading", text: "What Is a CV?", level: 2 },
      { type: "paragraph", text: "CV stands for Curriculum Vitae, Latin for 'course of life'. A CV is a comprehensive document covering your entire career history. It includes all your education, publications, research, presentations, awards, and professional experience. CVs are typically two to ten pages long and are common in the UK, Europe, the Middle East, Africa, and Asia — and in academic, medical, and research roles worldwide." },
      { type: "heading", text: "What Is a Resume?", level: 2 },
      { type: "paragraph", text: "A resume is a short, targeted document — usually one to two pages — that summarises only the most relevant experience and skills for a specific job. Resumes are the standard in the United States and Canada. They are tailored to the role and change from application to application." },
      { type: "heading", text: "Key Differences at a Glance", level: 2 },
      { type: "list", items: [
        "Length — CV: comprehensive, 2–10 pages. Resume: targeted, 1–2 pages",
        "Purpose — CV: complete career record. Resume: tailored for one specific role",
        "Geography — CV: UK, Europe, academia. Resume: US, Canada",
        "Content — CV includes publications, grants, conferences. Resume does not",
        "Photo — Optional in some CV traditions; never included on US resumes",
      ]},
      { type: "heading", text: "What About Personal Statements?", level: 2 },
      { type: "paragraph", text: "In UK universities and some graduate programmes, a personal statement is a separate document explaining why you are applying and what you bring to the role. This is different from the professional summary on a CV." },
      { type: "heading", text: "What Does CVPair Support?", level: 2 },
      { type: "paragraph", text: "CVPair supports both formats. Our templates can be used to create a short targeted resume (use Compact, Modern, or ATS templates) or a more detailed professional CV (use Classic, Harvard, Europass, or Executive templates). The builder works identically for both — you control how much or how little to include." },
      { type: "cta", text: "Create Your CV or Resume", href: "/resume", buttonText: "Open Builder" },
    ],
  },

  {
    slug: "best-skills-to-add-in-cv",
    title: "Best Skills to Add in Your CV in 2026",
    excerpt:
      "Knowing which skills to include — and how to list them — can make the difference between getting shortlisted and getting ignored.",
    category: "CV Writing",
    date: "Feb 22, 2026",
    readTime: "6 min read",
    author: "CVPair Team",
    image: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=1200&q=80",
    content_blocks: [
      { type: "paragraph", text: "Your skills section tells a recruiter — and the ATS — whether you are qualified for the role at a glance. A well-crafted skills section is concise, relevant, and backed by real experience. A bad one is a generic list of buzzwords that everyone else is also using." },
      { type: "heading", text: "Hard Skills vs Soft Skills", level: 2 },
      { type: "paragraph", text: "Hard skills are specific, teachable abilities: Python, Adobe Illustrator, financial modelling, HVAC systems. Soft skills are interpersonal or personal traits: communication, leadership, adaptability. Both matter, but hard skills are easier to verify and carry more weight in ATS screening." },
      { type: "heading", text: "High-Value Hard Skills by Industry", level: 2 },
      { type: "list", items: [
        "Technology: Python, SQL, React, cloud platforms (AWS/Azure/GCP), DevOps, machine learning",
        "Finance: Financial modelling, Excel, Bloomberg, QuickBooks, CFA designation",
        "Marketing: SEO, Google Analytics, Meta Ads, HubSpot, copywriting, A/B testing",
        "Healthcare: Electronic health records, patient assessment, clinical protocols, BLS/ACLS",
        "Design: Figma, Adobe Creative Suite, prototyping, user research, motion graphics",
        "Operations: Supply chain management, ERP systems (SAP/Oracle), process improvement, Lean/Six Sigma",
      ]},
      { type: "heading", text: "Soft Skills Worth Listing (If You Can Back Them Up)", level: 2 },
      { type: "list", items: [
        "Communication — especially for client-facing or leadership roles",
        "Project management — if you have managed timelines, budgets, or teams",
        "Problem-solving — strongest when paired with a specific example",
        "Adaptability — relevant in fast-moving environments or career transitions",
      ]},
      { type: "heading", text: "Skills to Remove From Your CV", level: 2 },
      { type: "list", items: [
        "'Microsoft Office' — assumed unless the role specifically requires Excel mastery",
        "'Hard worker' or 'team player' — tell a story instead",
        "Software you are not actually proficient in",
        "Skills that are unrelated to the role you are applying for",
      ]},
      { type: "heading", text: "How to Format Your Skills Section", level: 2 },
      { type: "paragraph", text: "List skills as a comma-separated line or a simple bulleted list. Group by category if you have many: Technical Skills, Languages, Tools. Avoid rating bars (Beginner / Expert) — they are subjective and often ignored." },
      { type: "callout", text: "CVPair's ATS checklist checks whether you have at least 5 skills listed. Aim for 8–14 specific, relevant skills." },
      { type: "cta", text: "Add Your Skills in CVPair", href: "/resume", buttonText: "Build Your CV" },
    ],
  },

  {
    slug: "how-to-write-resume-summary",
    title: "How to Write a Resume Summary That Gets Read",
    excerpt:
      "Your summary is the first thing a recruiter reads. Here is a proven formula to write one that is specific, compelling, and relevant.",
    category: "CV Writing",
    date: "Mar 1, 2026",
    readTime: "5 min read",
    author: "CVPair Team",
    image: "https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=1200&q=80",
    content_blocks: [
      { type: "paragraph", text: "A resume summary is a 2–4 line paragraph at the top of your CV that tells the hiring manager who you are and why you are the right candidate. It is the first thing they read — and in most cases, the deciding factor for whether they keep reading." },
      { type: "heading", text: "Summary vs Objective: What Is the Difference?", level: 2 },
      { type: "paragraph", text: "A resume objective ('I am looking for an opportunity to grow in a challenging environment') focuses on what you want. A summary focuses on what you offer. Employers care about what you bring to the role — not your career aspirations. Use a summary unless you are changing careers with no direct experience, in which case an objective can work." },
      { type: "heading", text: "The Formula for a Strong Summary", level: 2 },
      { type: "list", items: [
        "Line 1: Your professional title + years of experience + specialisation",
        "Line 2: Your strongest skill or area of expertise + relevant context",
        "Line 3: A specific achievement or value you bring (with a number if possible)",
      ]},
      { type: "heading", text: "Examples by Experience Level", level: 2 },
      { type: "callout", text: "Fresh Graduate: 'BSc Computer Science graduate with a strong foundation in Python and data analysis. Completed a 3-month internship at a fintech startup where I built an automated reporting tool that reduced manual processing time by 40%.'" },
      { type: "callout", text: "Mid-Level: 'Digital marketing specialist with 5 years of experience in SEO and paid media. Generated over £1.2M in attributed revenue through search campaigns for e-commerce clients across the UK and EU.'" },
      { type: "callout", text: "Senior / Executive: 'Operations director with 14 years of experience scaling supply chains in FMCG. Led a global logistics overhaul that cut distribution costs by 22% and improved on-time delivery from 81% to 97%.'" },
      { type: "heading", text: "Common Summary Mistakes", level: 2 },
      { type: "list", items: [
        "Being vague ('results-driven professional with strong interpersonal skills')",
        "Making it too long — more than 4 lines and recruiters skip it",
        "Writing in third person ('John is an experienced...')",
        "Repeating your job title without adding context",
        "Including objectives instead of value propositions",
      ]},
      { type: "cta", text: "Write Your Summary in CVPair", href: "/resume", buttonText: "Start Building" },
    ],
  },

  {
    slug: "cv-format-for-students",
    title: "CV Format for Students: How to Stand Out With No Experience",
    excerpt:
      "A practical guide for students writing their first CV — what to include, what to leave out, and how to make limited experience look impressive.",
    category: "CV Writing",
    date: "Mar 5, 2026",
    readTime: "6 min read",
    author: "CVPair Team",
    image: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=1200&q=80",
    content_blocks: [
      { type: "paragraph", text: "Writing your first CV as a student feels difficult — mostly because it feels like you have nothing to put in it. In reality, you have more than you think. The key is knowing what matters to employers and how to frame your experience convincingly." },
      { type: "heading", text: "What Employers Hiring Students Actually Look For", level: 2 },
      { type: "list", items: [
        "Reliability and commitment (shown through consistent work or activity history)",
        "Communication and teamwork (shown through group projects or clubs)",
        "Enthusiasm and willingness to learn (shown through tone and detail)",
        "Relevance (skills and experience that connect to the role)",
      ]},
      { type: "heading", text: "Student CV Structure", level: 2 },
      { type: "list", items: [
        "Contact details (name, email, phone, LinkedIn if you have one)",
        "Personal statement / summary (3–4 lines)",
        "Education (university course, A-levels, relevant modules or projects)",
        "Work experience (any paid or voluntary work)",
        "Skills (technical and transferable)",
        "Extracurricular activities (societies, sports teams, volunteer work)",
        "References available on request (optional)",
      ]},
      { type: "heading", text: "How to Write About University Projects", level: 2 },
      { type: "paragraph", text: "Projects are a legitimate form of experience. Describe what you built, what role you played, what tools you used, and what the outcome was. Example: 'Built a full-stack web application for a module project using React and Node.js, achieving a first-class grade. Managed the database design and API architecture for a team of three.'" },
      { type: "heading", text: "Include Part-Time and Casual Work", level: 2 },
      { type: "paragraph", text: "Working in retail, hospitality, or any other part-time role shows you can manage time, show up consistently, and work with people. Do not dismiss it. Instead, extract transferable skills: 'Managed high-volume customer service during peak hours, handling up to 200+ transactions per shift with 98% positive feedback.'" },
      { type: "heading", text: "Student CV Length and Format", level: 2 },
      { type: "paragraph", text: "Keep it to one page. Use a clean, readable template. Avoid photos, graphics, and decorative fonts. Save as PDF. Proofread twice." },
      { type: "cta", text: "Create Your Student CV", href: "/resume?compact", buttonText: "Use Compact Template" },
    ],
  },

  {
    slug: "resume-format-software-engineers",
    title: "Resume Format for Software Engineers",
    excerpt:
      "Software engineering resumes need to show technical depth, project impact, and clean formatting. Here is exactly how to structure yours.",
    category: "Industry Guides",
    date: "Mar 10, 2026",
    readTime: "7 min read",
    author: "CVPair Team",
    image: "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?auto=format&fit=crop&w=1200&q=80",
    content_blocks: [
      { type: "paragraph", text: "Software engineering is one of the most competitive job markets in the world. Your resume needs to communicate technical skill, impact, and clarity — all in a format that works with ATS and impresses a hiring manager in under 30 seconds." },
      { type: "heading", text: "Structure for a Software Engineer Resume", level: 2 },
      { type: "list", items: [
        "Contact info + GitHub/portfolio link",
        "Professional summary (2–3 lines)",
        "Technical skills (grouped by category)",
        "Work experience (reverse chronological)",
        "Projects (if adding value beyond experience)",
        "Education",
        "Certifications (optional)",
      ]},
      { type: "heading", text: "Technical Skills Section", level: 2 },
      { type: "paragraph", text: "Group your skills clearly. Recruiters and engineers scanning your CV want to quickly identify language fit. Example groupings:" },
      { type: "list", items: [
        "Languages: Python, TypeScript, Go, Rust",
        "Frameworks: React, Next.js, FastAPI, Django",
        "Cloud: AWS (EC2, Lambda, S3, RDS), Terraform",
        "Databases: PostgreSQL, Redis, DynamoDB",
        "Tools: Docker, Kubernetes, GitHub Actions, Datadog",
      ]},
      { type: "heading", text: "Writing Experience Bullets That Work", level: 2 },
      { type: "paragraph", text: "Tech bullets often fall into the trap of describing technologies instead of outcomes. Recruiters want to understand what you shipped and what it did." },
      { type: "callout", text: "Weak: 'Used React and Node.js to build a dashboard.' Strong: 'Built an analytics dashboard in React and Node.js used by 12,000 daily active users, reducing report generation time from 4 minutes to under 8 seconds.'" },
      { type: "heading", text: "Should You Include a Projects Section?", level: 2 },
      { type: "paragraph", text: "Yes — especially if you are early in your career or changing specialisation. List 2–3 projects with a one-line description, the technologies used, and a link to GitHub or a live demo. Personal projects demonstrate initiative and skills that your job history might not show." },
      { type: "heading", text: "Which Template to Use", level: 2 },
      { type: "paragraph", text: "Use CVPair's Developer template for a clean, technical-first layout with a strong projects section. For companies that use strict ATS, the Minimal ATS template is safer." },
      { type: "cta", text: "Build Your Engineering Resume", href: "/resume?developer", buttonText: "Use Developer Template" },
    ],
  },

  {
    slug: "resume-format-teachers",
    title: "Resume Format for Teachers",
    excerpt:
      "A teaching CV needs to show qualifications, classroom experience, subject specialisation, and the impact you have had on students.",
    category: "Industry Guides",
    date: "Mar 14, 2026",
    readTime: "6 min read",
    author: "CVPair Team",
    image: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=1200&q=80",
    content_blocks: [
      { type: "paragraph", text: "Whether you are applying for your first teaching position or moving to a new school, your CV needs to demonstrate more than subject knowledge. Schools look for candidates who can manage a classroom, engage students, and contribute to the wider school community." },
      { type: "heading", text: "Key Sections for a Teaching CV", level: 2 },
      { type: "list", items: [
        "Contact details",
        "Personal statement (3–5 lines tailored to the school and role)",
        "Qualifications and certifications (PGCE, QTS, DBS, subject degree)",
        "Teaching experience (school name, year groups, subjects)",
        "Key achievements (exam results, initiatives led)",
        "Skills (classroom management, curriculum planning, SEN experience)",
        "Professional development and CPD",
        "References (head teacher and another senior staff member)",
      ]},
      { type: "heading", text: "Write a Targeted Personal Statement", level: 2 },
      { type: "paragraph", text: "Schools receive dozens of applications and your personal statement is how you stand out. Mention the specific school by name, the year groups and subjects you are applying to teach, and one or two things you genuinely find compelling about education. Avoid generic statements about 'making a difference.'" },
      { type: "heading", text: "Show Classroom Impact", level: 2 },
      { type: "paragraph", text: "Wherever possible, include measurable outcomes. Examples:" },
      { type: "list", items: [
        "Improved Year 9 maths pass rates from 61% to 78% over two academic years",
        "Introduced a reading programme for SEN students that improved comprehension scores by an average of 1.5 grade levels",
        "Led an after-school STEM club with 24 students that won a regional robotics competition",
      ]},
      { type: "heading", text: "Include Your Qualifications Clearly", level: 2 },
      { type: "paragraph", text: "List your Qualified Teacher Status (QTS) or equivalent prominently. Include the institution where you completed your PGCE or teacher training, and the year. If you have a DBS certificate, mention it. Schools will verify all of these before making an offer." },
      { type: "cta", text: "Build Your Teaching CV", href: "/resume?classic", buttonText: "Use Classic Template" },
    ],
  },

  {
    slug: "resume-format-nurses",
    title: "Resume Format for Nurses",
    excerpt:
      "A nursing CV must clearly show your registration, clinical experience, specialisations, and certifications. Here is how to structure it.",
    category: "Industry Guides",
    date: "Mar 18, 2026",
    readTime: "6 min read",
    author: "CVPair Team",
    image: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=1200&q=80",
    content_blocks: [
      { type: "paragraph", text: "Nursing CVs are read by clinical managers, HR departments, and sometimes by automated applicant tracking systems. Your CV must immediately communicate your registration status, clinical competencies, and care experience in a clear and professional format." },
      { type: "heading", text: "Nursing CV Structure", level: 2 },
      { type: "list", items: [
        "Contact details",
        "NMC Pin / nursing registration number (include prominently)",
        "Professional summary (2–3 lines)",
        "Clinical experience (reverse chronological)",
        "Education and training (nursing degree, university, year)",
        "Certifications (BLS, ACLS, ILS, IV therapy, catheterisation, etc.)",
        "Key clinical skills",
        "References (two clinical referees)",
      ]},
      { type: "heading", text: "Always Include Your NMC Registration", level: 2 },
      { type: "paragraph", text: "Your NMC (Nursing and Midwifery Council) pin number is the first thing a recruiter will verify. Include it next to your name or in your contact section. If you are not yet registered, note 'NMC registration pending — expected [month/year].'" },
      { type: "heading", text: "Describe Clinical Experience Specifically", level: 2 },
      { type: "paragraph", text: "Avoid vague descriptions like 'provided patient care.' Instead, be specific about the ward or department, patient population, bed numbers, and your responsibilities. Example: 'Delivered care to up to 8 high-dependency patients per shift in a 24-bed surgical ward, including post-operative monitoring, wound care, and pain management protocols.'" },
      { type: "heading", text: "List All Relevant Certifications", level: 2 },
      { type: "list", items: [
        "Basic Life Support (BLS)",
        "Advanced Cardiac Life Support (ACLS)",
        "Immediate Life Support (ILS)",
        "IV therapy and cannulation",
        "Medication administration and PGDs",
        "Moving and handling",
        "Mental health first aid (if applicable)",
      ]},
      { type: "heading", text: "Tailor to Your Specialisation", level: 2 },
      { type: "paragraph", text: "Whether you work in A&E, paediatrics, theatre, ICU, community nursing, or mental health — tailor your skills and experience bullets to the specific area you are applying into. Generic nursing CVs rarely get interviews in specialist roles." },
      { type: "cta", text: "Build Your Nursing CV", href: "/resume?modern", buttonText: "Use Modern Template" },
    ],
  },

  {
    slug: "resume-format-accountants",
    title: "Resume Format for Accountants",
    excerpt:
      "An accountant's CV needs to lead with qualifications, highlight financial systems expertise, and quantify your impact on the businesses you have worked with.",
    category: "Industry Guides",
    date: "Mar 22, 2026",
    readTime: "6 min read",
    author: "CVPair Team",
    image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=1200&q=80",
    content_blocks: [
      { type: "paragraph", text: "Accounting is a profession where credentials matter as much as experience. Your CV needs to clearly communicate your qualifications, the financial systems and tools you have used, and the tangible improvements you have delivered for organisations." },
      { type: "heading", text: "Accounting CV Structure", level: 2 },
      { type: "list", items: [
        "Contact details",
        "Professional summary",
        "Professional qualifications (ACA, ACCA, CIMA, CPA — list clearly with status)",
        "Work experience",
        "Technical skills (accounting software, ERP systems)",
        "Education",
        "CPD and professional memberships",
      ]},
      { type: "heading", text: "Make Qualifications Prominent", level: 2 },
      { type: "paragraph", text: "Whether you are fully qualified, part-qualified, or studying, state it clearly near the top of your CV. 'ACCA Part-Qualified (4 of 13 exams passed, expected qualification June 2027)' tells a recruiter exactly where you are in your journey without ambiguity." },
      { type: "heading", text: "Technical Skills Section", level: 2 },
      { type: "paragraph", text: "Accounting employers look for proficiency in specific tools. List what you have actually used:" },
      { type: "list", items: [
        "Accounting software: Xero, QuickBooks, Sage, FreeAgent",
        "ERP systems: SAP, Oracle Financials, Microsoft Dynamics",
        "Spreadsheets: Advanced Excel (VLOOKUP, pivot tables, macros), Power BI",
        "Payroll: ADP, BambooHR",
        "Tax software: Thomson Reuters ONESOURCE, Alphatax",
      ]},
      { type: "heading", text: "Quantify Your Financial Impact", level: 2 },
      { type: "list", items: [
        "Managed monthly close process for a business with £18M annual turnover",
        "Identified £340,000 in recoverable VAT through a compliance audit",
        "Reduced month-end close time from 8 days to 4 days by automating journal entries",
        "Prepared consolidated financial statements for a group of 7 entities",
      ]},
      { type: "cta", text: "Build Your Accounting CV", href: "/resume?executive", buttonText: "Use Executive Template" },
    ],
  },

  {
    slug: "resume-format-graphic-designers",
    title: "Resume Format for Graphic Designers",
    excerpt:
      "Your CV as a designer should reflect your visual sensibility — without sacrificing ATS readability. Here is how to balance both.",
    category: "Industry Guides",
    date: "Mar 26, 2026",
    readTime: "5 min read",
    author: "CVPair Team",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1200&q=80",
    content_blocks: [
      { type: "paragraph", text: "Graphic designers face a unique challenge: their CV is a portfolio piece as well as a professional document. It needs to show visual skill while remaining readable, scannable, and often ATS-compatible for agencies and studios that use applicant tracking." },
      { type: "heading", text: "Always Lead With Your Portfolio", level: 2 },
      { type: "paragraph", text: "Before anything else, make your portfolio link impossible to miss. Include it next to your name at the top of your CV. It is the single most important thing a design recruiter will click on. Make sure it loads quickly and shows your best 5–8 pieces." },
      { type: "heading", text: "CV Structure for Designers", level: 2 },
      { type: "list", items: [
        "Name + portfolio URL + contact details",
        "Professional summary (what type of design work you specialise in)",
        "Key skills (software proficiency, design disciplines)",
        "Work experience (agency, in-house, or freelance)",
        "Notable projects or campaigns",
        "Education (degree or design foundation)",
        "Awards and recognition (if any)",
      ]},
      { type: "heading", text: "Software Skills Matter — Be Specific", level: 2 },
      { type: "list", items: [
        "Adobe Creative Suite: Photoshop, Illustrator, InDesign, After Effects, Premiere Pro",
        "UI/UX tools: Figma, Sketch, Adobe XD",
        "Motion and 3D: Cinema 4D, Blender, Lottie",
        "Print: Knowledge of print production, colour profiles, file prep for press",
        "Web: Basic HTML/CSS if applicable",
      ]},
      { type: "heading", text: "Describe Projects With Context", level: 2 },
      { type: "paragraph", text: "Do not just list where you worked. Describe what you designed, for whom, and what happened. Example: 'Designed a full brand identity for a Series A fintech startup — logo, typography system, colour palette, and marketing collateral — which was deployed across product, social, and investor materials used to raise £4.2M.'" },
      { type: "heading", text: "Creative vs ATS Template", level: 2 },
      { type: "paragraph", text: "If applying directly to studios or creative agencies, use a Creative or Sidebar template that shows visual flair. If applying through a recruiter or an ATS-heavy company, use a cleaner Modern or Classic template and let your portfolio do the creative talking." },
      { type: "cta", text: "Build Your Designer CV", href: "/resume?creative", buttonText: "Use Creative Template" },
    ],
  },

  {
    slug: "cover-letter-example-freshers",
    title: "Cover Letter Example for Freshers",
    excerpt:
      "Writing your first cover letter is daunting. This guide gives you a proven structure and a real example you can adapt for any entry-level role.",
    category: "Cover Letters",
    date: "Apr 1, 2026",
    readTime: "6 min read",
    author: "CVPair Team",
    image: "https://images.unsplash.com/photo-1586282391129-76a6df230234?auto=format&fit=crop&w=1200&q=80",
    content_blocks: [
      { type: "paragraph", text: "A cover letter is your chance to add personality and context to your CV. For freshers with limited experience, it is often the deciding factor — because it shows how you think, communicate, and why you specifically want this role." },
      { type: "heading", text: "Should Freshers Always Send a Cover Letter?", level: 2 },
      { type: "paragraph", text: "Yes — whenever one is requested, and often even when it is listed as optional. A well-written cover letter shows effort and enthusiasm that a CV alone cannot convey. Many hiring managers say they read cover letters specifically to shortlist between equally qualified fresh graduates." },
      { type: "heading", text: "Cover Letter Structure", level: 2 },
      { type: "list", items: [
        "Opening line: State the role and where you found it. Hook them immediately",
        "Paragraph 1: Why you are interested in this company or sector specifically",
        "Paragraph 2: What relevant skills or experience you bring (use specifics)",
        "Paragraph 3: What you bring beyond the CV — your motivation, work ethic, learning mindset",
        "Closing: Clear call to action and sign-off",
      ]},
      { type: "heading", text: "Example Cover Letter for a Fresh Graduate", level: 2 },
      { type: "callout", text: "Dear [Hiring Manager Name],\n\nI am writing to apply for the Junior Marketing Executive role at [Company], which I found on LinkedIn. I have followed your work in sustainable consumer goods for the past two years and I was excited to see this opening.\n\nI recently completed my BA in Marketing at the University of Leeds, where I specialised in digital marketing and consumer behaviour. During my final year, I ran social media accounts for the university's charity committee, growing our Instagram following by 340% in six months and raising £8,200 for our annual campaign — more than double the previous year's total.\n\nI am drawn to this role because it combines creative campaign thinking with data analysis — two areas I genuinely enjoy. I am comfortable with Google Analytics, Meta Ads Manager, and Canva, and I am a fast learner when it comes to new tools.\n\nI would welcome the chance to discuss how I can contribute to the team. Thank you for your time.\n\nYours sincerely,\n[Your Name]" },
      { type: "heading", text: "Common Cover Letter Mistakes to Avoid", level: 2 },
      { type: "list", items: [
        "Opening with 'I am writing to express my interest in...' — too generic",
        "Repeating everything on your CV — add context, not duplication",
        "Making it longer than one page",
        "Forgetting to name the company or role — shows you copied a template",
        "Not proofreading — errors in a cover letter are worse than on a CV",
      ]},
      { type: "cta", text: "Write Your Cover Letter in CVPair", href: "/resume", buttonText: "Open Cover Letter Builder" },
    ],
  },

  {
    slug: "how-to-explain-career-gap-in-resume",
    title: "How to Explain a Career Gap on Your CV",
    excerpt:
      "A gap in your CV is not an automatic dealbreaker. Here is how to address it honestly, position it confidently, and stop it from costing you interviews.",
    category: "Career Advice",
    date: "Apr 6, 2026",
    readTime: "6 min read",
    author: "CVPair Team",
    image: "https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?auto=format&fit=crop&w=1200&q=80",
    content_blocks: [
      { type: "paragraph", text: "Career gaps are more common than ever — parental leave, redundancy, illness, travel, mental health, or simply leaving a toxic environment. Recruiters are increasingly understanding of gaps. The key is addressing them proactively rather than hoping nobody notices." },
      { type: "heading", text: "Should You Try to Hide a Gap?", level: 2 },
      { type: "paragraph", text: "No. Hiding a gap by using only years instead of months (2021–2023) is often noticed and raises more questions than the gap itself. Be honest — most recruiters will ask about gaps in an interview anyway. Better to frame it on your terms." },
      { type: "heading", text: "Common Reasons for Career Gaps (All Valid)", level: 2 },
      { type: "list", items: [
        "Redundancy / company closure",
        "Parental leave or family caring responsibilities",
        "Illness, burnout, or mental health recovery",
        "Relocation or immigration",
        "Education or retraining",
        "Travel or sabbatical",
        "Personal circumstances",
      ]},
      { type: "heading", text: "How to Address a Gap on Your CV", level: 2 },
      { type: "paragraph", text: "If the gap was brief (under 3 months), you do not need to address it on the CV — the dates will cover it naturally. For longer gaps, add a single line in your experience section:" },
      { type: "list", items: [
        "Career Break — Parental Leave (June 2024 – Feb 2025)",
        "Career Break — Personal Health (March 2023 – October 2023)",
        "Sabbatical — Independent Study / Travel (2022 – 2023)",
        "Redundancy — Job Search (Jan 2025 – present)",
      ]},
      { type: "heading", text: "What If You Did Something Productive During the Gap?", level: 2 },
      { type: "paragraph", text: "Even better — mention it. Freelance work, volunteering, online courses, caregiving, or creative projects all show that you remained active and continued developing. Example: 'Career Break — completed Google Data Analytics Certificate and volunteered with a local charity's database project (January–August 2024).'" },
      { type: "heading", text: "In the Interview", level: 2 },
      { type: "paragraph", text: "Prepare a clear, confident one or two sentence explanation. Do not overshare or over-apologise. End on a forward-looking note: what you learned, what you did, and why you are excited to return to work. Practise saying it calmly so it does not sound rehearsed." },
      { type: "cta", text: "Build a CV That Handles Your Timeline", href: "/resume", buttonText: "Open CV Builder" },
    ],
  },

  {
    slug: "best-resume-fonts-and-layout",
    title: "Best Resume Fonts and Layout in 2026",
    excerpt:
      "The fonts and layout of your CV affect readability, ATS performance, and first impressions. Here is what to use — and what to avoid.",
    category: "CV Design",
    date: "Apr 10, 2026",
    readTime: "5 min read",
    author: "CVPair Team",
    image: "https://images.unsplash.com/photo-1586281380117-5a60ae2050cc?auto=format&fit=crop&w=1200&q=80",
    content_blocks: [
      { type: "paragraph", text: "Design choices on your CV are not cosmetic — they affect whether the document is readable, ATS-parseable, and whether the hiring manager gets a positive first impression. Here is what the evidence and recruiter feedback consistently says." },
      { type: "heading", text: "Best Fonts for CVs in 2026", level: 2 },
      { type: "paragraph", text: "Stick to professional, widely supported fonts. These are the top choices:" },
      { type: "list", items: [
        "Calibri — the Microsoft default, clean and highly readable at small sizes",
        "Georgia — elegant serif, works well for formal and academic CVs",
        "Garamond — classic and space-efficient, popular in consulting and law",
        "Helvetica / Arial — modern sans-serif, strong in tech and creative fields",
        "Lato or Source Sans Pro — modern choices for digital-first applications",
      ]},
      { type: "heading", text: "Fonts to Avoid", level: 2 },
      { type: "list", items: [
        "Times New Roman — outdated, seen as lazy default",
        "Comic Sans — never appropriate on a professional document",
        "Papyrus or decorative fonts — unreadable at small sizes",
        "Script or handwriting fonts — ATS cannot read them",
      ]},
      { type: "heading", text: "Font Size Rules", level: 2 },
      { type: "list", items: [
        "Your name: 18–24pt",
        "Section headings: 12–14pt, bold",
        "Body text: 10–11pt",
        "Contact details: 10pt",
        "Nothing below 9pt — recruiters read on screens and in print",
      ]},
      { type: "heading", text: "Margins and Spacing", level: 2 },
      { type: "paragraph", text: "Use 1.5–2cm margins on all sides. Line spacing of 1.15 to 1.5 makes bullets easier to scan. White space is not wasted space — it gives the eye a place to rest and makes your CV look less cluttered." },
      { type: "heading", text: "Colour on Your CV", level: 2 },
      { type: "paragraph", text: "A single accent colour for your name or section headings is fine and can add personality. Two or more accent colours starts to look distracting. For conservative industries (finance, law, medicine), stick to black and white. For creative roles, a single tasteful colour is appropriate." },
      { type: "callout", text: "CVPair uses professionally chosen fonts and spacing in every template. You never have to worry about sizing or margins — it is all set up for you." },
      { type: "cta", text: "Choose a CV Template", href: "/resume", buttonText: "Browse Templates" },
    ],
  },

  {
    slug: "how-long-should-a-cv-be",
    title: "How Long Should a CV Be?",
    excerpt:
      "One page or two? The answer depends on your experience level and industry. Here is exactly how to decide — and what to cut.",
    category: "CV Writing",
    date: "Apr 14, 2026",
    readTime: "5 min read",
    author: "CVPair Team",
    image: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=1200&q=80",
    content_blocks: [
      { type: "paragraph", text: "CV length is one of the most debated topics in job searching. The honest answer: there is no universal rule, but there are clear guidelines based on experience level and industry." },
      { type: "heading", text: "The Simple Guide by Experience Level", level: 2 },
      { type: "list", items: [
        "0–3 years experience: One page, always",
        "3–10 years experience: One to two pages",
        "10+ years experience: Two pages maximum (in most industries)",
        "Academic or medical CV: Can be longer — list publications, grants, and research",
      ]},
      { type: "heading", text: "When One Page Is Right", level: 2 },
      { type: "paragraph", text: "Students, fresh graduates, and career changers should always aim for one page. If you are stretching to fill two pages with weak content — thin bullets, excessive white space, or details nobody needs — one tight, focused page is always stronger." },
      { type: "heading", text: "When Two Pages Is Appropriate", level: 2 },
      { type: "paragraph", text: "Once you have 5+ years of substantive experience across multiple roles, two pages is not just acceptable — it is expected. Do not try to cram a decade of experience onto one page by using an 8pt font and no margins. That is worse than two clean pages." },
      { type: "heading", text: "What to Cut to Shorten Your CV", level: 2 },
      { type: "list", items: [
        "Roles more than 10–15 years ago (summarise as 'Early Career' if needed)",
        "Bullets that describe duties rather than achievements",
        "'References available on request' — this is assumed and wastes a line",
        "Secondary school results if you have a university degree",
        "Hobbies and interests unless directly relevant to the role",
        "Outdated technology skills (nobody needs to know you can use Windows XP)",
      ]},
      { type: "heading", text: "What About Three Pages?", level: 2 },
      { type: "paragraph", text: "Almost never appropriate for a standard job application. Three-page CVs signal poor editing judgment. The exception is a formal academic CV or a portfolio document — which follows different conventions entirely." },
      { type: "callout", text: "Use CVPair's Compact template if you need to fit strong content onto one page without it feeling squeezed." },
      { type: "cta", text: "Build a Focused, Well-Length CV", href: "/resume?compact", buttonText: "Try Compact Template" },
    ],
  },

  {
    slug: "how-to-write-experience-section-cv",
    title: "How to Write the Experience Section on Your CV",
    excerpt:
      "The experience section is the heart of your CV. Here is how to structure it, write compelling bullets, and show real impact.",
    category: "CV Writing",
    date: "Apr 18, 2026",
    readTime: "7 min read",
    author: "CVPair Team",
    image: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1200&q=80",
    content_blocks: [
      { type: "paragraph", text: "The experience section is where most hiring decisions are made. It is the section recruiters spend the most time on and the one most candidates write the worst. Here is how to make yours stand out." },
      { type: "heading", text: "The Right Format for Each Role", level: 2 },
      { type: "list", items: [
        "Company name (bold or prominent)",
        "Your job title",
        "Dates: Month Year – Month Year (or 'Present')",
        "Location (optional but useful for in-person or hybrid roles)",
        "3–6 bullet points",
      ]},
      { type: "heading", text: "How to Write a Strong Bullet Point", level: 2 },
      { type: "paragraph", text: "Every bullet should follow a simple pattern: Action verb + what you did + what happened as a result. The result does not have to be a number — but it should be something meaningful." },
      { type: "callout", text: "Weak: 'Responsible for the marketing team's email campaigns.' Strong: 'Rebuilt the email marketing programme for a list of 45,000 subscribers, increasing open rates from 18% to 31% and generating £94,000 in attributed revenue over 6 months.'" },
      { type: "heading", text: "Strong Action Verbs by Function", level: 2 },
      { type: "list", items: [
        "Leadership: Led, directed, managed, oversaw, coordinated",
        "Growth: Grew, expanded, increased, accelerated, scaled",
        "Improvement: Streamlined, reduced, optimised, improved, automated",
        "Creation: Built, designed, developed, launched, created",
        "Analysis: Analysed, evaluated, investigated, identified, reported",
        "Collaboration: Partnered, collaborated, aligned, facilitated, presented",
      ]},
      { type: "heading", text: "How Many Bullets per Role?", level: 2 },
      { type: "paragraph", text: "Three to five bullets for older or shorter roles. Five to six for your most recent or most relevant role. Do not include more than six — quality over quantity. If a bullet is weak, cut it rather than pad it." },
      { type: "heading", text: "How Far Back Should You Go?", level: 2 },
      { type: "paragraph", text: "Include the last 10–15 years in full. For roles beyond that, either cut them entirely or add a brief 'Earlier Career' section with just the company name, title, and year — no bullets needed." },
      { type: "heading", text: "Handling Multiple Roles at the Same Company", level: 2 },
      { type: "paragraph", text: "If you were promoted, list the company once and stack the roles below it with separate dates and bullets. This makes the progression clear without duplicating the company name." },
      { type: "cta", text: "Build Your Experience Section", href: "/resume", buttonText: "Open CV Builder" },
    ],
  },

  {
    slug: "linkedin-profile-vs-resume",
    title: "LinkedIn Profile vs Resume: Key Differences",
    excerpt:
      "Your LinkedIn and your CV serve different purposes. Here is what should be on each — and how to make them work together.",
    category: "Career Advice",
    date: "Apr 22, 2026",
    readTime: "6 min read",
    author: "CVPair Team",
    image: "https://images.unsplash.com/photo-1611944212129-29977ae1398c?auto=format&fit=crop&w=1200&q=80",
    content_blocks: [
      { type: "paragraph", text: "Many job seekers treat their LinkedIn profile and their CV as the same document in different places. They are not. Each platform has different audiences, different algorithms, and different content conventions." },
      { type: "heading", text: "The Core Difference", level: 2 },
      { type: "paragraph", text: "Your CV is targeted and concise — written for a specific role. Your LinkedIn profile is your public professional presence — it should be comprehensive, always up to date, and written to attract opportunity proactively. A recruiter might find your LinkedIn without you having applied for anything." },
      { type: "heading", text: "What Goes on LinkedIn But Not on a CV", level: 2 },
      { type: "list", items: [
        "A professional photo (never on a CV in most countries)",
        "Your full professional headline (optimised with keywords for LinkedIn search)",
        "A longer 'About' section — more personal, first-person narrative",
        "Recommendations from colleagues and managers",
        "Skills endorsed by your network",
        "Articles and posts you have published",
        "All education, certificates, volunteer work (no need to be selective)",
        "Featured section — portfolio pieces, presentations, press mentions",
      ]},
      { type: "heading", text: "What Goes on a CV But Not Necessarily on LinkedIn", level: 2 },
      { type: "list", items: [
        "A targeted professional summary written for the specific role",
        "Exact dates (month and year) in a specific format",
        "Quantified achievement bullets edited for the application",
        "A concise skills section curated for the role",
        "References section (kept off LinkedIn entirely)",
      ]},
      { type: "heading", text: "LinkedIn Headline Tips", level: 2 },
      { type: "paragraph", text: "Your LinkedIn headline is the most keyword-heavy real estate on your profile. Do not just put your job title. Add specialisations and the type of role you want next. Example: 'Senior Software Engineer | React · Node.js · AWS | Open to Senior & Staff roles in FinTech or SaaS.'" },
      { type: "heading", text: "Should They Match?", level: 2 },
      { type: "paragraph", text: "They should be consistent — same job titles, same dates, no contradictions. But they do not have to be identical. Recruiters will compare them if your application catches their eye. Discrepancies create doubt. Consistency builds trust." },
      { type: "cta", text: "Build a CV That Complements Your LinkedIn", href: "/resume", buttonText: "Open CV Builder" },
    ],
  },

  {
    slug: "free-resume-templates-for-job-seekers",
    title: "Free CV Templates for Job Seekers",
    excerpt:
      "CVPair offers 14 free professional CV templates for every industry and experience level. Here is how to choose the right one for your job search.",
    category: "Templates",
    date: "Apr 26, 2026",
    readTime: "5 min read",
    author: "CVPair Team",
    image: "https://images.unsplash.com/photo-1483058712412-4245e9b90334?auto=format&fit=crop&w=1200&q=80",
    content_blocks: [
      { type: "paragraph", text: "Choosing the right CV template is not just about aesthetics — it is about making sure your information is presented in the most effective structure for your experience level, industry, and the type of role you are targeting." },
      { type: "heading", text: "CVPair's Free Templates", level: 2 },
      { type: "paragraph", text: "All 14 templates on CVPair are completely free to use. No sign-up, no watermark, no paywall. You can switch between templates instantly with a live preview showing exactly how your content will look." },
      { type: "heading", text: "Which Template for Which Role", level: 2 },
      { type: "list", items: [
        "Modern — versatile choice for most professionals in tech, marketing, and business",
        "Classic — traditional layout for formal roles in law, finance, or academia",
        "Compact — ideal for fitting strong content onto one page",
        "Sidebar — shows skills and contact info in a side column; popular for creative and tech",
        "Executive — premium layout for senior management and C-suite",
        "Developer — projects-first layout for software engineers",
        "Timeline — visual career progression, good for storytelling-heavy roles",
        "Creative — split layout for designers, marketers, and portfolio-led roles",
        "MBA — business school and product management style",
        "Europass — standard European CV format for EU applications",
        "Harvard — classic academic layout used in graduate and research applications",
        "Consulting — sharp, metrics-focused for consulting and strategy roles",
        "Product Manager — impact-forward with space for product metrics",
        "Minimal ATS — ultra-clean for companies with strict ATS screening",
      ]},
      { type: "heading", text: "What Makes a Good CV Template?", level: 2 },
      { type: "list", items: [
        "Clear visual hierarchy — eyes should flow naturally from name → summary → experience",
        "ATS compatibility — no tables, text boxes, or image-based elements",
        "Appropriate for the industry — conservative templates for traditional roles, creative for design",
        "Enough space for content — avoid templates where the design overwhelms the substance",
      ]},
      { type: "heading", text: "Can I Use These Templates for Free?", level: 2 },
      { type: "paragraph", text: "Yes. Every template on CVPair is free to use, customise, and export as a PDF. There is no account required. Your CV is saved in your browser automatically. You can create multiple CVs and switch between them using the Resume Manager." },
      { type: "cta", text: "Browse All Free Templates", href: "/#templates", buttonText: "See Templates" },
    ],
  },

  {
    slug: "how-to-make-ats-friendly-resume",
    title: "How to Make an ATS-Friendly Resume",
    excerpt:
      "Most companies screen CVs through software before a human reads them. Here is exactly how to format yours to pass ATS filters and land interviews.",
    category: "Resume Tips",
    date: "May 2, 2026",
    readTime: "7 min read",
    author: "CVPair Team",
    image: "https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&w=1200&q=80",
    content_blocks: [
      { type: "paragraph", text: "Studies suggest that over 90% of Fortune 500 companies use applicant tracking systems (ATS) to filter CVs before any human reviews them. If your CV is not formatted to work with ATS, you may be screened out before a recruiter ever reads a word." },
      { type: "heading", text: "What ATS Software Actually Does", level: 2 },
      { type: "paragraph", text: "ATS software parses your CV into a structured database — extracting your name, contact details, job titles, employers, dates, skills, and education. It then scores your CV against the job description based on keyword match and other criteria. If your score is below the threshold, your CV is rejected automatically." },
      { type: "heading", text: "ATS-Friendly Formatting Rules", level: 2 },
      { type: "list", items: [
        "Use a single-column layout — multi-column formats often break parsers",
        "Avoid tables, text boxes, and graphics — ATS cannot read them",
        "Do not put contact info in headers or footers",
        "Use standard fonts (Calibri, Arial, Georgia)",
        "Save as .pdf or .docx — check the job posting for preference",
        "Use standard section headings (Work Experience, Education, Skills)",
      ]},
      { type: "heading", text: "Keyword Optimisation", level: 2 },
      { type: "paragraph", text: "Read the job description carefully and identify the key skills, tools, and phrases used. Incorporate them naturally throughout your CV — in your summary, skills section, and experience bullets. ATS matching is largely keyword-based, so the language you use matters." },
      { type: "callout", text: "Do not keyword-stuff. Pasting a list of keywords in white text (to hide them visually) is a trick ATS systems now detect and flag. Use keywords where they genuinely fit." },
      { type: "heading", text: "Test Your CV Before Applying", level: 2 },
      { type: "paragraph", text: "Use CVPair's built-in ATS checker to score your CV against 7 criteria before you submit. A score of 7/7 means your CV has all the core elements recruiters look for. You can also paste your CV into an online ATS simulator to see how it parses." },
      { type: "heading", text: "When ATS Rules Do Not Apply", level: 2 },
      { type: "paragraph", text: "Small companies, startups, agencies, and many creative businesses do not use ATS — applications go directly to a person. In these cases, a more visually distinctive CV may actually help. Read the job application process to gauge whether you are likely going through ATS." },
      { type: "cta", text: "Build an ATS-Optimised CV", href: "/resume?minimalAts", buttonText: "Use ATS Template" },
    ],
  },
];

export function getBlogPost(slug) {
  return blogPosts.find((post) => post.slug === slug) || null;
}
